Repository modm-io/modm, pull requests merged in 2019-06, with the labels that each got.

#224 Fix missing .fastdata copy for STM32 linkerscript
  src/modm/platform/core/cortex/linker.macros
  src/modm/platform/core/stm32/linkerscript/stm32_dccm.ld.in
  src/modm/platform/core/stm32/linkerscript/stm32_iccm.ld.in
  src/modm/platform/core/stm32/linkerscript/stm32_idtcm.ld.in
  src/modm/platform/core/stm32/linkerscript/stm32_ram.ld.in
Labels: enhancement 🌈, fix 💎

#226 Add support for CAN FMI on STM32
  examples/stm32f103c8t6_blue_pill/can/main.cpp
  src/modm/platform/can/stm32/can.cpp.in
  src/modm/platform/can/stm32/can.hpp.in
Labels: enhancement 🌈

#227 Fix ADC on Blue-Pill
  src/modm/board/black_pill/board.hpp
  src/modm/board/blue_pill/board.hpp
  src/modm/board/nucleo_f103rb/board.hpp
Labels: bug 🐞, fix 💎

#229 [ci] Redesign deployment of docs using workspaces
  .circleci/config.yml
Labels: enhancement 🌈
