Repository modm-io/modm, pull requests merged in 2019-05, with the labels that each got.

#202 Fix relpath in SCons AVRDUDE module
  tools/build_script_generator/scons/site_tools/program_avrdude.py
Labels: fix 💎, hosted 🖥

#204 [scons] Fix generated SConscript on Windows
  repo.lb
  tools/build_script_generator/gdbinit.in
  tools/build_script_generator/openocd.cfg.in
  tools/build_script_generator/scons/resources/SConscript.in
Labels: advanced 🤯, fix 💎, hosted 🖥

#207 [scons] Add Collectors for toolpath and tools
  tools/build_script_generator/scons/module.lb
  tools/build_script_generator/scons/resources/SConscript.in
Labels: enhancement 🌈

#213 [platform] Fix USART interrupts on a few AVRs
  src/modm/platform/uart/at90_tiny_mega/uart_defines.h
Labels: fix 💎

#214 [scons] Set default `tools` to empty
  tools/build_script_generator/scons/resources/SConstruct.in
Labels: enhancement 🌈, hosted 🖥
