Repository modm-io/modm, pull requests merged in 2019-11, with the labels that each got.

#311 [stm32] Fix STM32G4 pll setting
  src/modm/platform/clock/stm32/rcc.cpp.in
Labels: fix 💎

#313 [docs] Explicitly declare the lbuild module in docs
  docs/module.md.in
  tools/doc_generator/group.dox.in
Labels: documentation 📑, enhancement 🌈

#314 GraphicDisplay virtual methods
  src/modm/ui/display/graphic_display.hpp
Labels: enhancement 🌈

#317 Add filter to extract the ADC channel number only
  src/modm/platform/gpio/stm32/module.lb
  src/modm/platform/gpio/stm32/pin.hpp.in
  src/modm/platform/gpio/stm32/pin_f1.hpp.in
Labels: fix 💎
