Repository modm-io/modm, pull requests merged in 2019-09, with the labels that each got.

#274 Fix to isConversionFinished()
  src/modm/platform/adc/stm32f0/adc_impl.hpp.in
Labels: fix 💎

#277 [scons] Fix missing env.Listify for ITM tool
  tools/build_script_generator/scons/site_tools/log_itm.py
Labels: fix 💎, toolchain ⚙️

#279 [docs] Clarify placing applications into own folder
  docs/getting-started.md.in
Labels: documentation 📑, fix 💎

#288 [board] fix comment on L3GD20 MOSI pin
  src/modm/board/disco_f072rb/board.hpp
  src/modm/board/disco_f303vc/board.hpp
  src/modm/board/disco_f429zi/board.hpp
Labels: documentation 📑

#289 [scons] fix Windows path handling in "program"
  tools/build_script_generator/scons/resources/build_target.py.in
Labels: fix 💎

#291 Fixed condition in I2C ISR for continued writes
  src/modm/platform/i2c/stm32-extended/i2c_master.cpp.in
Labels: fix 💎

#293 [build] Add CompilationDB module
  .gitignore
  tools/build_script_generator/compilation_db/module.lb
  tools/build_script_generator/compilation_db/module.md
  tools/build_script_generator/compilation_db/resources/builder_compilation_db.py.in
  tools/build_script_generator/compilation_db/resources/compilation_db.py.in
  tools/build_script_generator/scons/module.lb
  tools/build_script_generator/scons/resources/SConscript.in
  tools/build_script_generator/scons/resources/SConstruct.in
  tools/build_script_generator/scons/resources/build_target.py.in
Labels: advanced 🤯, feature 🚧, lbuild 🏗, toolchain ⚙️
