Repository modm-io/modm, pull requests merged in 2019-07, with the labels that each got.

#236 [lbuild] Fix PathOption issue with absolute paths
  examples/lbuild.xml
  repo.lb
  test/all/avr.xml
  test/all/run_all.py
  test/all/stm32.xml
  test/config/lbuild.xml
  tools/build_script_generator/module.lb
  tools/build_script_generator/scons/module.lb
  tools/build_script_generator/scons/resources/SConstruct.in
  tools/xpcc_generator/module.lb
Labels: fix 💎

#240 [openocd] Do not hardcode user options in built-in configs
  examples/stm32f030f4p6_demo_board/blink/openocd.cfg
  examples/stm32f030f4p6_demo_board/blink/project.xml
  examples/stm32f103c8t6_black_pill/blink/openocd.cfg
  examples/stm32f103c8t6_black_pill/blink/project.xml
  examples/stm32f103c8t6_blue_pill/adns_9800/openocd.cfg
  examples/stm32f103c8t6_blue_pill/adns_9800/project.xml
  examples/stm32f103c8t6_blue_pill/blink.cmake/openocd.cfg
  examples/stm32f103c8t6_blue_pill/blink.cmake/project.xml
  examples/stm32f103c8t6_blue_pill/blink/openocd.cfg
  examples/stm32f103c8t6_blue_pill/blink/project.xml
  examples/stm32f103c8t6_blue_pill/can/openocd.cfg
  examples/stm32f103c8t6_blue_pill/can/project.xml
  examples/stm32f103c8t6_blue_pill/environment/openocd.cfg
  examples/stm32f103c8t6_blue_pill/environment/project.xml
  examples/stm32f103c8t6_blue_pill/logger/openocd.cfg
  examples/stm32f103c8t6_blue_pill/logger/project.xml
  src/modm/board/black_pill/module.lb
  src/modm/board/blue_pill/module.lb
  src/modm/board/stm32f030f4p6_demo/module.lb
  tools/build_script_generator/module.lb
  tools/build_script_generator/openocd.cfg.in
  tools/openocd/modm/stm32f030_demo_board.cfg
  tools/openocd/modm/stm32f103_blue_pill.cfg
Labels: enhancement 🌈, fix 💎

#244 Bugfix: STM32 acknowledge of interrupt clears all pending bits
  src/modm/platform/gpio/stm32/pin.hpp.in
  src/modm/platform/gpio/stm32/pin_f1.hpp.in
Labels: fix 💎

#247 Fix openocd makefile
  tools/build_script_generator/cmake/module.lb
  tools/build_script_generator/cmake/resources/Makefile.in
  tools/build_script_generator/module.lb
  tools/build_script_generator/openocd.cfg.in
  tools/build_script_generator/openocd_gdbinit.in
  tools/build_script_generator/scons/module.lb
Labels: fix 💎

#249 Changed to AdcInterrupts behavior
  src/modm/platform/adc/stm32/adc_interrupt.cpp.in
  src/modm/platform/adc/stm32/adc_interrupt.hpp.in
  src/modm/platform/adc/stm32/adc_shared_interrupts.cpp.in
  src/modm/platform/adc/stm32/module.lb
Labels: fix 💎

#254 [ci] Remove Python 2
  .circleci/config.yml
Labels: process 📊

#255 [docs] Use only Python 3 with macOS
  docs/src/guide/installation.md
  examples/stm32f103c8t6_blue_pill/environment/log.py
  examples/zmq/3_zmq_app/sub.py
  src/modm/ui/display/font/SConscript.generate
  src/modm/ui/display/image/SConscript.generate
  tools/bitmap/pbm2c.py
  tools/build_script_generator/scons/site_tools/log_itm.py
  tools/build_script_generator/scons/site_tools/program_openocd.py
  tools/font_creator/SConstruct
  tools/scripts/examples_compile.py
Labels: feature 🚧

#264 [cmake] First define the compiler before further detection
  tools/build_script_generator/cmake/cmake_scripts/configure-gcc.cmake.in
  tools/build_script_generator/cmake/resources/CMakeLists.txt.in
Labels: fix 💎, toolchain ⚙️
