Repository modm-io/modm, pull requests merged in 2020-03, with the labels that each got.

#339 Added getEnabledInterrupts.
  src/modm/platform/timer/stm32/general_purpose.hpp.in
Labels: enhancement 🌈

#337 Add parameters for more control over general purpose timer CR1.
  src/modm/platform/timer/stm32/general_purpose.cpp.in
  src/modm/platform/timer/stm32/general_purpose.hpp.in
Labels: enhancement 🌈

#338 Added TimerX::isChannelConfiguredAsInput.
  src/modm/platform/timer/stm32/general_purpose.cpp.in
  src/modm/platform/timer/stm32/general_purpose.hpp.in
Labels: enhancement 🌈

#347 Clear ADC interrupt flags when starting a conversion
  src/modm/platform/adc/stm32f3/adc_impl.hpp.in
Labels: fix 💎

#344 Added dummy parameter to Timer::isChannelConfiguredAsInput for 1 channel
  src/modm/platform/timer/stm32/general_purpose.hpp.in
Labels: enhancement 🌈

#350 [math] Add modm::range() inspired by Python
  src/modm/math/algorithm/range.hpp
  test/modm/math/algorithm/range_test.cpp
  test/modm/math/algorithm/range_test.hpp
Labels: feature 🚧

#356 [docs] Fix path for modm-test repo
  tools/doc_generator/doxyfile.cfg.in
  tools/doc_generator/doxypress.json.in
Labels: fix 💎

#361 [stm32] Clock: pass pll factors as struct
  src/modm/platform/clock/stm32/rcc.cpp.in
  src/modm/platform/clock/stm32/rcc.hpp.in
Labels: enhancement 🌈
