Repository modm-io/modm, pull requests merged in 2020-05, with the labels that each got.

#394 Explicitly set the stack pointer in the reset handler.
  src/modm/platform/core/cortex/reset_handler.sx
Labels: fix 💎

#371 STM32 DMA rework
  src/modm/platform/dma/stm32/dma.cpp.in
  src/modm/platform/dma/stm32/dma.hpp.in
  src/modm/platform/dma/stm32/dma_base.hpp.in
  src/modm/platform/dma/stm32/dma_hal.hpp.in
  src/modm/platform/dma/stm32/dma_hal_impl.hpp.in
  src/modm/platform/dma/stm32/dma_impl.hpp.in
  src/modm/platform/dma/stm32/module.lb
Labels: advanced 🤯, feature 🚧

#400 [spi] Enhance STM32 SPI with DMA support
  examples/nucleo_l432kc/spi_dma/main.cpp
  examples/nucleo_l432kc/spi_dma/project.xml
  src/modm/board/nucleo_l432kc/board.hpp
  src/modm/platform/spi/stm32/module.lb
  src/modm/platform/spi/stm32/spi_base.hpp.in
  src/modm/platform/spi/stm32/spi_hal.hpp.in
  src/modm/platform/spi/stm32/spi_hal_impl.hpp.in
  src/modm/platform/spi/stm32/spi_master_dma.hpp.in
  src/modm/platform/spi/stm32/spi_master_dma_impl.hpp.in
Labels: advanced 🤯, example 🔑, feature 🚧

#401 How to create a SystemClock struct
  src/modm/board/module.md
Labels: documentation 📑

#403 Fixes __wrap__free_r() to ignore freeing null pointers.
  src/modm/platform/heap/cortex/heap_tlsf.cpp
Labels: fix 💎

#404 [scons] add command-line arguments to manipulate CCFLAGS,CFLAGS,etc
  tools/build_script_generator/scons/resources/SConscript.in
Labels: toolchain ⚙️

#407 [spi] Fix writing SPI data size into correct register
  src/modm/platform/spi/stm32/spi_hal_impl.hpp.in
  src/modm/platform/spi/stm32/spi_master.hpp.in
Labels: fix 💎

#408 Derive iterators from std::iterator
  src/modm/container/deque.hpp
  src/modm/container/doubly_linked_list.hpp
  src/modm/container/dynamic_array.hpp
  src/modm/container/linked_list.hpp
Labels: enhancement 🌈

#405 moving BDTR related code to GeneralPurpose
  src/modm/platform/timer/stm32/advanced_base.hpp.in
  src/modm/platform/timer/stm32/general_purpose.hpp.in
  src/modm/platform/timer/stm32/general_purpose_base.hpp.in
Labels: enhancement 🌈
