Repository modm-io/modm, pull requests merged in 2020-06, with the labels that each got.

#413 Different Clock Config for Nucleo F042K6 to fix UART timings
  src/modm/board/nucleo_f042k6/board.hpp
Labels: fix 💎

#420 STM32 DAC Platform Driver
  src/modm/platform/dac/stm32/dac.hpp
  src/modm/platform/dac/stm32/dac_impl.hpp
  src/modm/platform/dac/stm32/module.lb
  src/modm/platform/gpio/stm32/pin.hpp.in
Labels: feature 🚧

#422 Added checks for tx and rx calls
  src/modm/driver/radio/sx1276.hpp
  src/modm/driver/radio/sx1276_definitions.hpp
  src/modm/driver/radio/sx1276_impl.hpp
Labels: enhancement 🌈

#425 Patches for arm32v7
  src/modm/io/iostream.hpp.in
  src/modm/platform/core/cortex/assert.cpp.in
  tools/build_script_generator/common.py
Labels: enhancement 🌈, hosted 🖥, toolchain ⚙️
