Repository modm-io/modm, pull requests merged in 2020-09, with the labels that each got.

#455 Fix FreeRTOS stack overflow hook
  ext/aws/modm_port.cpp
Labels: fix 💎

#454 Stm32 tim gp en out
  src/modm/platform/timer/stm32/general_purpose.hpp.in
Labels: fix 💎

#456 Update and simplify installation instructions for linux
  docs/mkdocs.yml
  docs/src/guide/installation.md
Labels: documentation 📑, enhancement 🌈, toolchain ⚙️

#463 [rpi] Remove stray #endif
  src/modm/platform/gpio/rpi/base.hpp
Labels: fix 💎

#457 [docs] Installation improvements
  docs/src/guide/installation.md
Labels: documentation 📑

#484 [driver] :bug: Fix ILI9341 and add SPI example for it
  examples/stm32f103c8t6_blue_pill/graphics/main.cpp
  examples/stm32f103c8t6_blue_pill/graphics/openocd.cfg
  examples/stm32f103c8t6_blue_pill/graphics/project.xml
  src/modm/driver/display/ili9341.hpp
Labels: example 🔑, fix 💎
