Repository modm-io/modm, pull requests merged in 2020-08, with the labels that each got.

#442 Fix the method isConversionFinished() to wait on EndOfConversion instead of EndOfSampling.
  src/modm/platform/adc/stm32f3/adc_impl.hpp.in
Labels: fix 💎

#443 fixed issue with escaping of arguments for size script
  tools/build_script_generator/cmake/resources/CMakeLists.txt.in
Labels: fix 💎, toolchain ⚙️

#452 Fix the CPU clock speed used in FreeRTOS.
  ext/aws/FreeRTOSConfig.h.in
Labels: fix 💎

#453 Use an integer instead of scientific notation. In some cases the 1e6 caused error during lbuild run.
  src/modm/platform/clock/stm32/rcc.cpp.in
Labels: fix 💎, lbuild 🏗
