Repository modm-io/modm, pull requests merged in 2020-11, with the labels that each got.

#502 Github Actions: add-path command was deprecated
  .github/workflows/macos.yml
  .github/workflows/windows_armcortexm.yml
  .github/workflows/windows_hosted.yml
Labels: fix 💎

#500 [example] Fix hint in comment about ITM
  examples/nucleo_f103rb/itm/main.cpp
  examples/nucleo_f303re/itm/main.cpp
Labels: example 🔑, fix 💎

#498 Add fastcode attribute to delay_ns
  src/modm/platform/core/cortex/delay_impl.hpp.in
Labels: enhancement 🌈, fix 💎

#511 [hosted] Fix include of boost bind in serial_port.hpp
  src/modm/platform/uart/hosted/serial_port.hpp
Labels: fix 💎
