Repository modm-io/modm, pull requests merged in 2020-04, with the labels that each got.

#373 [test] Move mock ups to common modm-test:mock:* modules
  test/Makefile
  test/all/run_all.py
  test/config/al-avreb-can.xml
  test/config/arduino-nano.xml
  test/config/arduino-uno.xml
  test/config/hosted.xml
  test/config/lbuild.xml
  test/config/nucleo-f103.xml
  test/config/nucleo-f401.xml
  test/config/nucleo-f411.xml
  test/config/nucleo-f446.xml
  test/config/nucleo-l432.xml
  test/modm/architecture/driver/clock_test.cpp
  test/modm/architecture/module.lb
  test/modm/communication/module.lb
  test/modm/communication/sab/interface_test.cpp
  test/modm/communication/sab/slave_test.cpp
  test/modm/communication/sab/slave_test.hpp
  test/modm/communication/xpcc/dispatcher_test.cpp
  test/modm/container/module.lb
  test/modm/driver/adc/ad7280a_test.cpp
  test/modm/driver/adc/spi_device_test.cpp
  test/modm/driver/module.lb
  test/modm/driver/motor/drv832x_spi_test.cpp
  test/modm/driver/temperature/ltc2984_test.cpp
  test/modm/io/module.lb
  test/modm/math/module.lb
  test/modm/mock/clock_dummy.cpp
  test/modm/mock/clock_dummy.hpp
  test/modm/mock/io_device.cpp
  test/modm/mock/io_device.hpp
  test/modm/mock/module.lb
  test/modm/mock/spi_device.cpp
  test/modm/mock/spi_device.hpp
  test/modm/mock/spi_master.cpp
  test/modm/mock/spi_master.hpp
  test/modm/mock/testing_clock.cpp
  test/modm/mock/testing_clock.hpp
  test/modm/platform/gpio/module.lb
  test/modm/platform/module.lb
  test/modm/platform/spi/mock/module.lb
  test/modm/processing/module.lb
  test/modm/processing/timer/periodic_timer_test.cpp
  test/modm/processing/timer/timeout_test.cpp
  test/modm/ui/module.lb
Labels: enhancement 🌈, testing 🧪

#376 Feature/bsp for nucleo f303re
  .circleci/config.yml
  README.md
  examples/nucleo_f303re/blink/main.cpp
  examples/nucleo_f303re/blink/project.xml
  examples/nucleo_f303re/itm/main.cpp
  examples/nucleo_f303re/itm/project.xml
  examples/nucleo_f303re/rtos/main.cpp
  examples/nucleo_f303re/rtos/project.xml
  src/modm/board/nucleo_f303re/board.hpp
  src/modm/board/nucleo_f303re/board.xml
  src/modm/board/nucleo_f303re/module.lb
Labels: example 🔑, feature 🚧

#386 Remove zeromq as it is not maintained anymore and broken.
  .circleci/config.yml
  docs/src/guide/installation.md
  examples/linux/xpcc/basic/component_receiver/receiver.cpp
  examples/linux/xpcc/basic/component_receiver/receiver.hpp
  examples/linux/xpcc/basic/component_sender/sender.cpp
  examples/linux/xpcc/basic/component_sender/sender.hpp
  examples/linux/xpcc/basic/main.cpp
  examples/linux/xpcc/basic/project.xml
  examples/zmq/1_stm32/component_odometry/odometry.cpp
  examples/zmq/1_stm32/component_odometry/odometry.hpp
  examples/zmq/1_stm32/main.cpp
  examples/zmq/1_stm32/project.xml
  examples/zmq/2_zmq_gateway/main.cpp
  examples/zmq/2_zmq_gateway/project.xml
  examples/zmq/3_zmq_app/component_gui/gui.cpp
  examples/zmq/3_zmq_app/component_gui/gui.hpp
  examples/zmq/3_zmq_app/main.cpp
  examples/zmq/3_zmq_app/project.xml
  examples/zmq/3_zmq_app/sub.py
  examples/zmq/4_zmq_backtoback/main.cpp
  examples/zmq/4_zmq_backtoback/project.xml
  examples/zmq/README.md
  src/modm/communication/xpcc/backend/zeromq.hpp
  src/modm/communication/xpcc/backend/zeromq/connector.cpp
  src/modm/communication/xpcc/backend/zeromq/connector.hpp
  src/modm/communication/xpcc/backend/zeromq/reader.cpp
  src/modm/communication/xpcc/backend/zeromq/reader.hpp
  src/modm/communication/xpcc/module.lb
Labels: deprecation 🧹, enhancement 🌈

#389 [timer] Fix time_point cast for short versions
  src/modm/processing/timer/periodic_timer.hpp
  src/modm/processing/timer/timeout.hpp
  src/modm/processing/timer/timeout_impl.hpp
  test/modm/processing/timer/timeout_test.cpp
Labels: fix 💎

#388 Fix reception of messages from CAN2USB
  src/modm/platform/can/canusb/canusb.hpp
  src/modm/platform/can/canusb/canusb_impl.hpp
Labels: fix 💎
