Repository modm-io/modm, pull requests merged in 2020-02, with the labels that each got.

#281 Doxypress API documentation on https://docs.modm.io/
  .circleci/config.yml
  README.md
  docs/src/reference/documentation.md
  tools/doc_generator/doxypress.json.in
  tools/doc_generator/module.lb
  tools/doc_generator/module.md
  tools/scripts/docs_modm_io_generator.py
  tools/scripts/docs_modm_io_index.html.in
  tools/scripts/generate_module_docs.py
Labels: advanced 🤯, documentation 📑, feature 🚧, lbuild 🏗, process 📊, toolchain ⚙️

#333 Add links to Anaconda and Miniconda in Windows installation guide.
  docs/src/guide/installation.md
Labels: documentation 📑

#334 Add missing module for example in Getting Started documentation.
  docs/getting-started.md.in
Labels: documentation 📑

#331 Move the check for I2C NACKF to the event handler
  src/modm/platform/i2c/stm32-extended/i2c_master.cpp.in
Labels: advanced 🤯, fix 💎
