Repository modm-io/modm, pull requests merged in 2021-12, with the labels that each got.

#791 Integration of RTT example from stm32f3_discovery to blue_pill_f103
  examples/blue_pill_f103/rtt/main.cpp
  examples/blue_pill_f103/rtt/openocd.cfg
  examples/blue_pill_f103/rtt/project.xml
Labels: example 🔑

#790 [rtt] Zero SRAM when using RTT
  tools/build_script_generator/openocd.cfg.in
Labels: advanced 🤯, fix 💎

#785 [fix] gdb.py signal handler for linux
  tools/modm_tools/gdb.py
Labels: advanced 🤯, fix 💎

#780 [fix] modm::Saturated
  src/modm/math/saturated/saturated.hpp
  src/modm/math/saturated/saturated__avr_s8_impl.hpp
  src/modm/math/saturated/saturated__avr_u8_impl.hpp
  src/modm/math/saturated/saturated_impl.hpp
  src/modm/math/saturation/saturated.hpp
  src/modm/math/saturation/saturation.lb
  src/modm/math/utils/integer_traits.hpp
  test/modm/math/module.lb
  test/modm/math/saturated/saturated_test.cpp
  test/modm/math/saturation/saturation_test.cpp
  test/modm/math/saturation/saturation_test.hpp
Labels: enhancement 🌈, feature 🚧

#795 [stm32] Fix off-by-one error in exti irq handler
  src/modm/platform/extint/stm32/exti.hpp.in
Labels: fix 💎, ci:hal
