Repository modm-io/modm, pull requests merged in 2021-05, with the labels that each got.

#626 [board] Add modm:board:nucleo-f072rb
  .github/workflows/linux.yml
  README.md
  examples/nucleo_f072rb/blink/main.cpp
  examples/nucleo_f072rb/blink/project.xml
  src/modm/board/disco_f072rb/board.hpp
  src/modm/board/nucleo_f072rb/board.hpp
  src/modm/board/nucleo_f072rb/board.xml
  src/modm/board/nucleo_f072rb/module.lb
Labels: ci:hal, example 🔑, feature 🚧

#616 Refactor modm:ui:color
  examples/arduino_nano/color/main.cpp
  examples/avr/display/dogm128/benchmark/main.cpp
  examples/avr/display/dogm128/draw/main.cpp
  examples/blue_pill_f103/graphics/main.cpp
  examples/nucleo_f446re/color/main.cpp
  examples/nucleo_l452re/graphics_touch/main.cpp
  examples/nucleo_l452re/lvgl/main.cpp
  examples/stm32_f4ve/gui/main.cpp
  examples/stm32f469_discovery/display/main.cpp
  examples/stm32f469_discovery/game_of_life/main.cpp
  examples/stm32f469_discovery/touchscreen/main.cpp
  examples/stm32f4_discovery/colour_tcs3414/main.cpp
  examples/stm32f4_discovery/open407v-d/gui/main.cpp
  examples/stm32f4_discovery/open407v-d/touchscreen/main.cpp
  src/modm/board/disco_f469ni/board_display.cpp
  src/modm/driver/color/tcs3414.hpp
  src/modm/driver/color/tcs3472.hpp
  src/modm/driver/display/ili9341.hpp
  src/modm/driver/display/ili9341_impl.hpp
  src/modm/driver/display/parallel_tft.hpp
  src/modm/driver/display/parallel_tft_impl.hpp
  src/modm/ui/color.hpp
  src/modm/ui/color/brightness.hpp
  src/modm/ui/color/color.lb
  src/modm/ui/color/hsv.hpp
  src/modm/ui/color/hsv_impl.hpp
  src/modm/ui/color/rgb.hpp
  src/modm/ui/color/rgb565.hpp
  src/modm/ui/color/rgb_impl.hpp
  src/modm/ui/color/rgbhtml.hpp
  src/modm/ui/display/color_graphic_display.hpp
  src/modm/ui/display/graphic_display.hpp
  src/modm/ui/display/graphic_display_text.cpp
  src/modm/ui/display/module.lb
  src/modm/ui/display/virtual_graphic_display.cpp
  src/modm/ui/display/virtual_graphic_display.hpp
  src/modm/ui/gui/colorpalette.cpp
  src/modm/ui/gui/colorpalette.hpp
  src/modm/ui/gui/widgets/button.hpp
  src/modm/ui/gui/widgets/label.hpp
  src/modm/ui/gui/widgets/widget.hpp
  src/modm/ui/led/rgb.hpp
  test/modm/ui/color/color_test.cpp
  test/modm/ui/color/color_test.hpp
  test/modm/ui/module.lb
Labels: ci:hal, refactor 🔥

#635 [openocd] Upgrade deprecated TPIU+ITM configuration
  examples/nucleo_f103rb/itm/main.cpp
  examples/nucleo_f303re/itm/main.cpp
  src/modm/platform/uart/cortex/itm.cpp.in
  src/modm/platform/uart/cortex/itm.hpp.in
  src/modm/platform/uart/cortex/module.lb
  src/modm/platform/uart/cortex/module.md
  tools/build_script_generator/openocd.cfg.in
Labels: advanced 🤯, ci:hal, fix 💎

#636 [examples] blue-pill ITM logging
  examples/blue_pill_f103/itm/main.cpp
  examples/blue_pill_f103/itm/openocd.cfg
  examples/blue_pill_f103/itm/project.xml
Labels: example 🔑

#637 [tests] Use MODM_ARRAY_SIZE()
  test/modm/math/filter/moving_average_test.cpp
Labels: fix 💎, testing 🧪
