Repository modm-io/modm, pull requests merged in 2021-07, with the labels that each got.

#644 2021q2 release
  CHANGELOG.md
  docs/release/2021q2.md
Labels: documentation 📑, process 📊

#651 [core] Much longer modm::delay_ms on Cortex-M
  src/modm/architecture/interface/delay.hpp
  src/modm/architecture/interface/delay.md
  src/modm/platform/core/avr/delay_impl.hpp.in
  src/modm/platform/core/avr/module.md
  src/modm/platform/core/cortex/delay.cpp.in
  src/modm/platform/core/cortex/delay_impl.hpp.in
  src/modm/platform/core/cortex/delay_ns.cpp.in
  src/modm/platform/core/hosted/delay_impl.hpp.in
Labels: ci:hal, fix 💎

#649 [stm32] Add calibration for F1 ADC
  src/modm/platform/adc/stm32/adc.hpp.in
  src/modm/platform/adc/stm32/adc_impl.hpp.in
Labels: ci:hal, feature 🚧

#654 mmc5603.hpp correction: swapDataFloat shouldn't call itself
  src/modm/driver/inertial/mmc5603.hpp
Labels: fix 💎

#656 [animation] add missing dependency to :processing:timer
  src/modm/ui/animation/base.hpp
  src/modm/ui/animation/module.lb
Labels: fix 💎

#658 [stm32] Fix noisy compiler warnings in uart driver for g4
  src/modm/platform/uart/stm32/uart_base.hpp.in
Labels: ci:hal, fix 💎

#662 [processing] Add RF_INTERNAL_END() to processing/resumable/makros.hpp
  src/modm/processing/resumable/macros.hpp
Labels: enhancement 🌈
