Repository modm-io/modm, pull requests merged in 2021-09, with the labels that each got.

#677 Fix SAMD GPIO bug for port B
  src/modm/platform/gpio/sam/pin.hpp
Labels: fix 💎, ci:hal

#679 Support USB device on samg family
  README.md
  examples/samg55_xplained_pro/blink/project.xml
  examples/samg55_xplained_pro/usbserial/main.cpp
  examples/samg55_xplained_pro/usbserial/project.xml
  ext/hathach/module.lb
  src/modm/board/samg55_xplained_pro/board.hpp
  src/modm/board/samg55_xplained_pro/module.lb
  src/modm/platform/clock/samg/clockgen.hpp
  src/modm/platform/clock/samg/clockgen_impl.hpp
  src/modm/platform/usb/sam/module.lb
  src/modm/platform/usb/sam/usb.hpp.in
Labels: feature 🚧, ci:hal

#680 Add SPI driver for samg family
  README.md
  examples/samg55_xplained_pro/spi-loopback/main.cpp
  examples/samg55_xplained_pro/spi-loopback/project.xml
  src/modm/platform/clock/samg/clockgen.hpp
  src/modm/platform/gpio/sam/pin.hpp.in
  src/modm/platform/spi/sam/module.lb
  src/modm/platform/spi/sam/spi_master.cpp.in
  src/modm/platform/spi/sam/spi_master.hpp.in
Labels: feature 🚧, ci:hal

#683 Fix an incorrect include path which worked in most cases
  src/modm/platform/dac/stm32/dac.hpp.in
Labels: fix 💎

#688 [cortex-m] Enable FPU before startup script
  src/modm/platform/core/cortex/module.lb
  src/modm/platform/core/cortex/reset_handler.sx.in
  src/modm/platform/core/cortex/startup.c.in
Labels: advanced 🤯, fix 💎, toolchain ⚙️, ci:hal
