Repository modm-io/modm, pull requests merged in 2021-03, with the labels that each got.

#577 [ui] Support to stream color::HsvT like color::RgbT
  src/modm/ui/color.hpp
  src/modm/ui/color_impl.hpp
Labels: enhancement 🌈

#581 [driver] Fix inconsistencies in TCS34xx
  examples/nucleo_f446re/color/main.cpp
  src/modm/driver/color/tcs3472_impl.hpp
Labels: enhancement 🌈

#584 [bugfix] Add a short delay to loop in HD77480::writeCRGAM()
  src/modm/driver/display/hd44780_base_impl.hpp
Labels: fix 💎

#585 [avrdude] Adjust arduino-nano upload baudrate to 115200
  src/modm/board/arduino_nano/module.lb
Labels: fix 💎

#587 [avr] Add default fuses to BSPs and documentation for scons program-fuses
  src/modm/board/al_avreb_can/board_fuses.cpp
  src/modm/board/al_avreb_can/module.lb
  src/modm/board/arduino_uno/board_fuses.cpp
  src/modm/board/mega_2560_pro/board_fuses.cpp
  src/modm/platform/core/avr/main.hpp
  tools/build_script_generator/scons/module.md
  tools/modm_tools/avrdude.py
Labels: advanced 🤯, documentation 📑, enhancement 🌈
