Repository modm-io/modm, pull requests merged in 2021-04, with the labels that each got.

#605 [docs] Fix dark mode on homepage
  docs/mkdocs.yml
Labels: ci:hal, documentation 📑, fix 💎

#606 [docs] Fix table width for HAL matrix
  docs/mkdocs.yml
  docs/src/extra.css
  tools/scripts/generate_module_docs.py
Labels: documentation 📑, fix 💎

#612 [tinyusb] Only read from CDC if data is available
  examples/generic/usb/main.cpp
  ext/hathach/uart.hpp
Labels: ci:hal, fix 💎

#618 [stm32] Fix missing dependency of rcc driver on architecture:delay
  src/modm/platform/clock/stm32/module.lb
Labels: ci:hal, fix 💎

#623 Improved registers for tcs3472, tcs3414
  examples/arduino_nano/color/main.cpp
  src/modm/driver/color/tcs3414.hpp
  src/modm/driver/color/tcs3472.hpp
Labels: ci:hal, enhancement 🌈
