Repository modm-io/modm, pull requests merged in 2021-01, with the labels that each got.

#527 Fix unintended paragraph in documentation.
  README.md
Labels: documentation 📑, fix 💎

#531 [test] Fix angle_test on AVR
  test/modm/math/geometry/angle_test.cpp
Labels: fix 💎, testing 🧪

#534 [usb] Fix USB version in descriptors
  ext/hathach/tusb_descriptors.c.in
Labels: advanced 🤯, fix 💎

#532 [stm32] Fix F0/F1 PLL pre-divider setting
  src/modm/platform/clock/stm32/module.lb
  src/modm/platform/clock/stm32/rcc.cpp.in
  src/modm/platform/clock/stm32/rcc.hpp.in
Labels: advanced 🤯, fix 💎

#538 [stm32] Fixed TIM2 and TIM5 generated as 32 bit timer on stm32g4
  src/modm/platform/timer/stm32/general_purpose.hpp.in
Labels: fix 💎

#540 [delay] Fix register constraints for subs.n instruction
  src/modm/platform/core/cortex/delay_impl.hpp.in
Labels: advanced 🤯, fix 💎

#545 fix typo
  tools/modm_tools/gdb.py
Labels: fix 💎
