Repository modm-io/modm, pull requests merged in 2021-02, with the labels that each got.

#555 fix: configure USB::Id as PullUp in add to OpenDrain
  src/modm/platform/usb/stm32/usb.hpp.in
Labels: advanced 🤯, fix 💎

#559 adding support for usb exemple on STM32F072B-Disco
  examples/generic/usb/project.xml
  src/modm/board/disco_f072rb/board.hpp
  src/modm/board/disco_f072rb/module.lb
Labels: example 🔑, question ❔

#565 [docs] Fix docs for STM32F4 with ethernet
  ext/aws/module.lb
  tools/scripts/docs_modm_io_generator.py
Labels: fix 💎
