Repository modm-io/modm, pull requests merged in 2022-09, with the labels that each got.

#909 [build] Search for GCC >=10 on macOS, including 12
  tools/build_script_generator/make/resources/compiler.mk.in
  tools/build_script_generator/scons/resources/SConscript.in
Labels: fix 💎, toolchain ⚙️

#911 [platform] [stm32] [timer] Add one pulse mode to advanced timers
  src/modm/platform/timer/stm32/advanced.cpp.in
  src/modm/platform/timer/stm32/advanced.hpp.in
Labels: enhancement 🌈, ci:hal

#913 [stm32] [timer] [fix] Match template to default method
  src/modm/platform/timer/stm32/advanced.hpp.in
Labels: enhancement 🌈, ci:hal

#914 fixed filter moving average for floating type
  src/modm/math/filter/moving_average.hpp
Labels: fix 💎
