Repository modm-io/modm, pull requests merged in 2022-05, with the labels that each got.

#856 [stm32] Uart: Add transmission complete flag
  src/modm/platform/uart/stm32/uart_hal.hpp.in
  src/modm/platform/uart/stm32/uart_hal_impl.hpp.in
Labels: enhancement 🌈, ci:hal

#858 [stm32] add Half Transfer handler for dma
  src/modm/platform/dma/stm32/dma.hpp.in
Labels: feature 🚧

#859 proposal to add SlaveModeTrigger::Internal0 on F4
  src/modm/platform/timer/stm32/general_purpose.hpp.in
Labels: enhancement 🌈, ci:hal

#861 [board] Add Can1 and Can2 to Board::SystemClock
  src/modm/board/nucleo_f446re/board.hpp
  src/modm/board/nucleo_f446ze/board.hpp
Labels: enhancement 🌈, fix 💎

#862 [board] Update information about board revisions of F469NI Disco.Kits
  src/modm/board/disco_f469ni/module.lb
  src/modm/board/disco_f469ni/module.md
Labels: enhancement 🌈

#866 fix modm:platform:itm
  src/modm/platform/uart/cortex/itm.cpp.in
Labels: fix 💎

#869 Update adc_interrupt.cpp.in
  src/modm/platform/adc/at90_tiny_mega/adc_interrupt.cpp.in
Labels: fix 💎, ci:hal
