Repository modm-io/modm, pull requests merged in 2022-01, with the labels that each got.

#798 [stm32] Do not reset RCR register when configuring timer channel
  src/modm/platform/timer/stm32/advanced.cpp.in
Labels: fix 💎, ci:hal

#801 [docs] Show older releases on docs.modm.io
  tools/scripts/docs_modm_io_generator.py
  tools/scripts/docs_modm_io_index.html.in
Labels: documentation 📑

#809 [docs] Update AVR toolchain install instruction
  docs/src/guide/installation.md
Labels: documentation 📑

#813 Changed tilde by $HOME variable due to lack of expansion
  docs/src/guide/installation.md
Labels: documentation 📑, fix 💎
