Repository modm-io/modm, pull requests merged in 2022-02, with the labels that each got.

#822 [sam] GPIO setOutput overrides peripheral control
  src/modm/platform/gpio/sam/pin.hpp.in
Labels: enhancement 🌈, fix 💎, ci:hal

#823 [sam] Add driver for SAMG timer channels
  README.md
  examples/samg55_xplained_pro/timer/main.cpp
  examples/samg55_xplained_pro/timer/openocd.cfg
  examples/samg55_xplained_pro/timer/project.xml
  src/modm/board/samg55_xplained_pro/board.hpp
  src/modm/platform/timer/samg/module.lb
  src/modm/platform/timer/samg/timer_channel.hpp.in
  src/modm/platform/timer/samg/timer_channel_base.hpp
Labels: advanced 🤯, feature 🚧, ci:hal

#832 [docs] Document MODM_DEBUG_BUILD macro behavior
  src/modm/architecture/detect.hpp
  src/modm/architecture/interface/assert.md
  tools/build_script_generator/module.md
Labels: enhancement 🌈, documentation 📑
