Repository modm-io/modm, pull requests merged in 2023-03, with the labels that each got.

#964 [stm32] [dma] [irq] Always inline IRQ handler to reduce IRQ latency
  src/modm/platform/dma/stm32/dma.hpp.in
Labels: enhancement 🌈

#976 create method to enable and disable scan mode
  src/modm/platform/adc/stm32/adc.hpp.in
  src/modm/platform/adc/stm32/adc_impl.hpp.in
Labels: enhancement 🌈, ci:hal

#970 [xpcc] Separate the rx handling part of the update fct of the dispatcher
  src/modm/communication/xpcc/dispatcher.cpp
  src/modm/communication/xpcc/dispatcher.hpp.in
Labels: enhancement 🌈, advanced 🤯

#986 [sam] Fix SAMx7x systick frequency
  src/modm/platform/clock/systick/module.lb
Labels: fix 💎
