Repository modm-io/modm, pull requests merged in 2023-05, with the labels that each got.

#968 C++23 and C23
  README.md
  docs/mkdocs.yml
  docs/src/guide/installation.md
  tools/build_script_generator/common.py
  tools/build_script_generator/module.md
  tools/doc_generator/doxypress.json.in
  tools/ide/vscode/c_cpp_properties.json.in
Labels: toolchain ⚙️

#1014 [ci] Fix MacOS workflow
  .github/workflows/macos.yml
Labels: toolchain ⚙️

#1021 [test] Remove fiber availability on ARM64 targets
  src/modm/processing/fiber/module.lb
  test/modm/processing/module.lb
Labels: fix 💎

#1000 [sam] Fix compiler warnings for GpioUnused in SoftwareGpioPort
  src/modm/platform/gpio/sam/unused.hpp
Labels: fix 💎

#1022 [stm32] Fix I2C number bug
  src/modm/platform/i2c/stm32-extended/i2c_master.cpp.in
Labels: fix 💎, ci:hal

#1025 [driver] Set can_message.dlc field when receiving
  src/modm/driver/can/can_lawicel_formatter.cpp
  test/modm/driver/can/can_lawicel_formatter_test.cpp
Labels: fix 💎

#1027 [stm32] Timer fix: avoid arithmetic overflow in setPeriod
  src/modm/platform/timer/stm32/general_purpose.hpp.in
Labels: fix 💎

#1029 fixing bug #1024
  src/modm/ui/display/monochrome_graphic_display_impl.hpp
Labels: fix 💎
