Repository modm-io/modm, pull requests merged in 2023-09, with the labels that each got.

#1067 [ci] Split STM32G0 compile all job into two
  .github/workflows/compile-all.yml
Labels: enhancement 🌈, testing 🧪, ci:hal

#1069 [board] Default putchar_ to use the board logger
  examples/stm32f469_discovery/printf/main.cpp
  src/modm/board/board.cpp.in
  src/modm/board/module.md
Labels: fix 💎

#1063 [driver] Implement QMC5883L driver
  README.md
  examples/avr/qmc5883l/main.cpp
  examples/avr/qmc5883l/project.xml
  src/modm/driver/inertial/qmc5883l.hpp
  src/modm/driver/inertial/qmc5883l.lb
Labels: feature 🚧, example 🔑

#1080 LM75 temp sensor: fix utils/endianness dependency
  src/modm/driver/temperature/lm75.hpp
  src/modm/driver/temperature/lm75.lb
Labels: fix 💎

#1082 [docs] Update macOS installation of toolchain
  docs/src/guide/installation.md
Labels: documentation 📑, fix 💎, toolchain ⚙️
