Repository modm-io/modm, pull requests merged in 2023-07, with the labels that each got.

#1048 [stm32] Place .data section into D1_SRAM instead of DTCM for H7
  src/modm/platform/core/cortex/linker.macros
  src/modm/platform/core/cortex/ram.ld.in
  src/modm/platform/core/stm32/dccm.ld.in
  src/modm/platform/core/stm32/iccm.ld.in
  src/modm/platform/core/stm32/idtcm.ld.in
  src/modm/platform/core/stm32/module.md
  src/modm/platform/core/stm32/ram_remap_vector_table.ld.in
Labels: fix 💎

#1051 shared IRQ handling for fdcan on STM32G0
  README.md
  src/modm/platform/can/stm32-fdcan/can.cpp.in
  src/modm/platform/can/stm32-fdcan/can.hpp.in
  src/modm/platform/can/stm32-fdcan/can_shared_irqs.cpp.in
  src/modm/platform/can/stm32-fdcan/module.lb
Labels: feature 🚧

#1053 [stm32] Fix STM32G0 ADC
  src/modm/platform/adc/stm32f0/adc_impl.hpp.in
Labels: fix 💎, ci:hal
