Repository modm-io/modm, pull requests merged in 2024-08, with the labels that each got.

#1196 [fiber] Improve timing of poll functions
  src/modm/processing/fiber/functions.hpp
  test/modm/processing/fiber/fiber_test.cpp
Labels: enhancement 🌈, fix 💎

#1191 Fix GCC 13 __FPU_PRESENT redefinition warning
  ext/arm/arm_math.h.in
  ext/arm/arm_math_types.h.in
  ext/arm/cmsis.md
  ext/arm/dsp.lb
  ext/arm/dsp.md
Labels: fix 💎

#1189 Fix python syntax in modm_tools
  tools/modm_tools/avrdude.py
  tools/modm_tools/bmp.py
  tools/modm_tools/bossac.py
  tools/modm_tools/build_id.py
  tools/modm_tools/elf2uf2.py
  tools/modm_tools/itm.py
  tools/modm_tools/jlink.py
  tools/modm_tools/openocd.py
  tools/modm_tools/rtt.py
  tools/modm_tools/size.py
Labels: fix 💎, toolchain ⚙️

#1204 [iwdg] Enable IWDG on STM32H7 devices
  README.md
  src/modm/platform/iwdg/stm32/iwdg.hpp.in
  src/modm/platform/iwdg/stm32/module.lb
Labels: enhancement 🌈
