Repository modm-io/modm, pull requests merged in 2024-03, with the labels that each got.

#1135 Add disco_f411ve
  README.md
  examples/generic/usb/project.xml
  src/modm/board/disco_f411ve/board.hpp
  src/modm/board/disco_f411ve/board.xml
  src/modm/board/disco_f411ve/module.lb
Labels: feature 🚧, example 🔑

#1138 [driver] Adding AS5047 driver and example
  README.md
  examples/nucleo_g474re/as5047/main.cpp
  examples/nucleo_g474re/as5047/project.xml
  src/modm/driver/encoder/as5047.hpp
  src/modm/driver/encoder/as5047.lb
  src/modm/driver/encoder/as5047_impl.hpp
Labels: feature 🚧, example 🔑

#1139 [stm32] add advanced initialize on iwdg
  src/modm/platform/iwdg/stm32/iwdg.hpp
Labels: feature 🚧

#1143 [stm32] i2c irq priority can be set
  src/modm/platform/i2c/stm32-extended/i2c_master.cpp.in
  src/modm/platform/i2c/stm32-extended/i2c_master.hpp.in
Labels: enhancement 🌈, ci:hal

#1148 [stm32/sam_x7x] Allow I2C interrupt priority to be set
  src/modm/platform/i2c/sam_x7x/i2c_master.cpp.in
  src/modm/platform/i2c/sam_x7x/i2c_master.hpp.in
  src/modm/platform/i2c/stm32/i2c_master.cpp.in
  src/modm/platform/i2c/stm32/i2c_master.hpp.in
Labels: enhancement 🌈, ci:hal

#1152 Couple of fixes for BlackMagicProbe
  tools/modm_tools/bmp.py
  tools/modm_tools/utils.py
Labels: enhancement 🌈, fix 💎, toolchain ⚙️
