Repository modm-io/modm, pull requests merged in 2024-12, with the labels that each got.

#1236 [stm32] Use SCB_CleanInvalidateDCache() on startup
  src/modm/platform/core/cortex/startup.c.in
Labels: advanced 🤯, fix 💎

#1241 [scons] Fix duplicates in SConscript for external lbuild repos
  tools/build_script_generator/scons/resources/SConscript.in
  tools/build_script_generator/scons/site_tools/gcc_retarget.py
Labels: enhancement 🌈, toolchain ⚙️

#1243 [ci] Cancel previous in progress CI jobs
  .github/workflows/compile-all.yml
  .github/workflows/deploy-docs.yml
  .github/workflows/linux.yml
  .github/workflows/macos.yml
  .github/workflows/windows.yml
Labels: process 📊, testing 🧪
