Repository modm-io/modm, pull requests merged in 2024-07, with the labels that each got.

#1179 Fix minor typo in driver/encoder/as5600.lb
  src/modm/driver/encoder/as5600.lb
Labels: documentation 📑, fix 💎

#1183 add missing indent in openocd.py
  tools/modm_tools/openocd.py
Labels: fix 💎, toolchain ⚙️

#1192 Add option to specify which repositories to generate SConscript files for
  tools/build_script_generator/scons/module.lb
Labels: enhancement 🌈, fix 💎

#1194 [utils] Deprecate allocator::Dynamic for std::allocator
  src/modm/communication/rpr/interface.hpp
  src/modm/communication/rpr/interface_impl.hpp
  src/modm/container/module.lb
  src/modm/utils/allocator.hpp
Labels: deprecation 🧹
