Repository modm-io/modm, pull requests merged in 2024-11, with the labels that each got.

#1220 [linux] Enable SocketCAN to receive FDCan frames
  src/modm/platform/can/socketcan/socketcan.cpp
Labels: enhancement 🌈, fix 💎

#1222 Enable D-Cache for Cortex-M7
  src/modm/platform/core/cortex/module.md
  src/modm/platform/core/cortex/startup.c.in
Labels: enhancement 🌈, advanced 🤯

#1223 [stm32] Prevent SPI RX FIFO overflow in SPI master
  src/modm/platform/spi/stm32h7/spi_master.cpp.in
Labels: advanced 🤯, fix 💎

#1226 [container] Fix reducing capacity to 0 on DynamicArray::clear()
  src/modm/container/dynamic_array.hpp
Labels: fix 💎

#1230 [stm32] Disable MASRX in STM32H7 SPI
  src/modm/platform/spi/stm32h7/spi_hal_impl.hpp.in
Labels: advanced 🤯, fix 💎

#1231 fixed lvgl example for nucleo-l452re
  examples/nucleo_l452re/lvgl/main.cpp
Labels: fix 💎, example 🔑

#1234 [iwdg] Fix reversed prescaler enum index for STM32
  src/modm/platform/iwdg/stm32/iwdg.hpp.in
Labels: fix 💎
