Repository modm-io/modm, pull requests merged in 2025-01, with the labels that each got.

#1248 [release] Update changelog for 2024q4 release
  .mailmap
  CHANGELOG.md
  docs/release/2024q4.md
  tools/scripts/authors.py
Labels: documentation 📑, process 📊

#1252 [stm32] add missing HSI48-related functionality
  src/modm/platform/clock/stm32/module.lb
  src/modm/platform/clock/stm32/rcc.hpp.in
Labels: enhancement 🌈, advanced 🤯, fix 💎, ci:hal

#1254 fix #1253 - CMake program target .elf path is wrong
  tools/build_script_generator/cmake/resources/ModmConfiguration.cmake.in
Labels: fix 💎, toolchain ⚙️
